apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-webhook-url
  namespace: prometheus
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: ntfy-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: 70995233-d4da-4942-b503-b383015ba29f
        property: value
