apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Piotr1215/homelab
    targetRevision: HEAD
    path: gitops/apps/ntfy-alertmanager
  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy-alertmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
