apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: talks-tailscale
  namespace: talks-tracker
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - talks
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: talks-tracker
                port:
                  number: 80
