apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskchampion-tailscale
  namespace: taskchampion
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - taskchampion
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskchampion-sync-server
                port:
                  number: 8080
