---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-token
  namespace: prometheus
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: grafana-admin-token
    creationPolicy: Owner
    template:
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: 1119aa49-df5d-499c-8051-b397012d8e14
      property: value
