apiVersion: v1
kind: Service
metadata:
  name: sre-demo
  namespace: sre-demo
  labels:
    app: sre-demo
spec:
  type: ClusterIP
  selector:
    app: sre-demo
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
