apiVersion: v1
kind: Service
metadata:
  name: mcp-agentic-framework
  labels:
    app.kubernetes.io/name: mcp-agentic-framework
    app.kubernetes.io/instance: mcp-agentic-framework
spec:
  type: ClusterIP
  ports:
    - port: 3113
      targetPort: 3113
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mcp-agentic-framework
    app.kubernetes.io/instance: mcp-agentic-framework
---
apiVersion: v1
kind: Service
metadata:
  name: mcp-agentic-framework-lb
  labels:
    app.kubernetes.io/name: mcp-agentic-framework
    app.kubernetes.io/instance: mcp-agentic-framework
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.178.95"
spec:
  type: LoadBalancer
  ports:
    - port: 3113
      targetPort: 3113
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mcp-agentic-framework
    app.kubernetes.io/instance: mcp-agentic-framework
