{{- if .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "httproute-webhook.fullname" . }}
  labels:
    {{- include "httproute-webhook.labels" . | nindent 4 }}
spec:
  secretName: {{ include "httproute-webhook.fullname" . }}-tls
  dnsNames:
  - {{ include "httproute-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  - {{ include "httproute-webhook.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
{{- end }}
