apiVersion: v1
kind: Service
metadata:
  name: {{ include "httproute-webhook.fullname" . }}
  labels:
    {{- include "httproute-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: webhook
    protocol: TCP
    name: webhook
  selector:
    {{- include "httproute-webhook.selectorLabels" . | nindent 4 }}
