apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "httproute-webhook.fullname" . }}
  labels:
    {{- include "httproute-webhook.labels" . | nindent 4 }}
  {{- if .Values.webhook.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "httproute-webhook.fullname" . }}
  {{- end }}
webhooks:
- name: service.httproute.homelab.local
  admissionReviewVersions: ["v1"]
  clientConfig:
    service:
      name: {{ include "httproute-webhook.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-service
      port: {{ .Values.service.port }}
  failurePolicy: {{ .Values.webhook.failurePolicy }}
  matchPolicy: Equivalent
  namespaceSelector:
    {{- toYaml .Values.webhook.namespaceSelector | nindent 4 }}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["services"]
    scope: "*"
  sideEffects: None
  timeoutSeconds: 10
