apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - audit-latest-tag.yaml
  - audit-missing-resources.yaml
  - require-ro-rootfs.yaml
  - add-default-labels.yaml
  - block-host-namespaces.yaml
  - audit-privileged.yaml
